build:
  image: docker:19.03.12
  stage: build
  services:
    - docker:19.03.12-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/group/project/image:latest .
    - docker push $CI_REGISTRY/group/project/image:latest

image: docker:latest
#variables:
  #DOCKER_HOST: tcp://localhost:2375
variables:
  DOCKER_DRIVER: overlay2



before_script:
  - apk update
  - apk add curl nmap maven 
  #- apk add docker-ce docker-compose -y

after_script:
  - echo "finish"


build1:
  stage: build
  script:
    - touch test.txt
    - echo "Do your build here" > test.txt
  artifacts:
    paths:
      - test.txt
    expire_in: 3 week
    

    
test1:
  image: docker:19.03.12
  stage: test
  services:
    - docker:19.03.12-dind
  script:
    - DATETIME=$(date '+%m%d%y%H%M%S')
    - echo $DATETIME
    - docker -v
    - echo "Do a test here"
    - ls -lah
    - docker build -t testkapitan.eva.ua:443/firstgitlabci:$DATETIME .
    - docker push testkapitan.eva.ua:443/firstgitlabci:$DATETIME
    - cat test.txt

deploy1:
  stage: deploy
  script:
    #- docker-compose up -d
    - echo "Do your deploy here"
