image: ubuntu:18.04

before_script:
  - whoami
  - cat nsswitch.conf
  - cat /etc/passwd
  - apt-get update -y & apt-get upgrade -y
  - apt-get install maven -y
  - echo "For example you might run an update here or install a build dependency"
  - echo "Or perhaps you might print out some debugging details"

after_script:
  - ls -lh

build1:
  stage: build
  script:
    - echo "Do your build here"

test1:
  stage: test
  script:
    - echo "Do a test here"
    - echo "For example run a test suite"

test2:
  stage: test
  script:
    - echo "Do another parallel test here"
    - echo "For example run a lint test"

deploy1:
  stage: deploy
  script:
    - echo "Do your deploy here"
