image: ubuntu:latest

before_script:
  - apt update -y
  - apt install curl nmap maven -y
  - echo "Before script section"
  - echo "For example you might run an update here or install a build dependency"
  - echo "Or perhaps you might print out some debugging details"

after_script:
  - echo "After script section"
  - echo "For example you might do some cleanup here"

build1:
  stage: build
  script:
    - touch test.txt
    - echo "Do your build here" > test.txt
  artifacts:
    paths:
      - test.txt
    expire_in: 3 week
    
    
test1:
  stage: test
  script:
    - curl ipinfo.io/ip
    - mvn --version
    - echo "Do a test here"
    - ls -lah
    - cat test.txt


deploy1:
  stage: deploy
  script:
    - echo "Do your deploy here"
