#image: docker:latest
#variables:
  #DOCKER_HOST: tcp://localhost:2375
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"



before_script:
  - ls -la
  - apk add curl 
  - apk add docker-compose

after_script:
  - echo "finish"


build1:
  stage: build
  script:
    - touch test.txt
    - echo "Do your build here" > test.txt
  artifacts:
    paths:
      - test.txt
    expire_in: 3 week
    

    
test1:
  image: docker:stable
  stage: test
  services:
    - docker:19.03.12-dind
  script:
    - DATETIME=$(date '+%m%d%y%H%M%S')
    - echo $DATETIME
    - docker -v
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin
    - echo "Do a test here"
    - ls -lah
    - sed -i 's@CONTAINER_IMAGE@'"firstgitlabci:$DATETIME"'@' docker-compose.yaml
    - docker build -t kapitanmf/firstgitlabci:$DATETIME .
    - docker push kapitanmf/firstgitlabci:$DATETIME
    - cat test.txt

deploy1:
  stage: deploy
  script:
    - docker-compose up -d
    #- echo "Do your deploy here"
