image: ubuntu:latest

before_script:
  - apt update -y
  - apt install curl nmap maven docker-ce docker-compose apt-transport-https ca-certificates software-properties-common -y


after_script:
  - echo "finish"


build1:
  stage: build
  script:
    - touch test.txt
    - echo "Do your build here" > test.txt
  artifacts:
    paths:
      - test.txt
    expire_in: 3 week
    
    
test1:
  stage: test
  script:
    - curl ipinfo.io/ip
    - mvn --version
    - docker -v
    - echo "Do a test here"
    - ls -lah
    - docker ps
    - cat test.txt


deploy1:
  stage: deploy
  script:
    - echo "Do your deploy here"
